"""CTT-105 tabla metricas_idempotencia

Revision ID: 239c72c4c89c
Revises: 662bdf3507de
Create Date: 2026-08-14 18:27:40.300323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239c72c4c89c'
down_revision: Union[str, Sequence[str], None] = '662bdf3507de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metricas_idempotencia',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('replays', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('fecha', name=op.f('pk_metricas_idempotencia'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metricas_idempotencia')
    # ### end Alembic commands ###
