"""CTT-105: tabla claves_idempotencia

Revision ID: 662bdf3507de
Revises: fd2352cb63a2
Create Date: 2026-08-14 13:29:34.756731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '662bdf3507de'
down_revision: Union[str, Sequence[str], None] = 'fd2352cb63a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claves_idempotencia',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('estado', sa.Enum('en_proceso', 'completado', name='idempotencia_estado', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_claves_idempotencia_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claves_idempotencia')),
    sa.UniqueConstraint('empresa_id', 'idempotency_key', name='uq_claves_idempotencia_empresa_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claves_idempotencia')
    # ### end Alembic commands ###
