"""initial schema

Revision ID: 6aae58b445da
Revises: 
Create Date: 2026-07-19 00:02:17.345477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aae58b445da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('rut_empresa', sa.String(length=20), nullable=False),
    sa.Column('email_contacto', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.Enum('trial', 'basic', 'pro', name='plan', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'suspendido', 'trial', name='estado', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresas')),
    sa.UniqueConstraint('rut_empresa', name=op.f('uq_empresas_rut_empresa'))
    )
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'inactivo', name='estado', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('es_super_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email')),
    sa.UniqueConstraint('firebase_uid', name=op.f('uq_usuarios_firebase_uid')),
    sa.UniqueConstraint('rut', name=op.f('uq_usuarios_rut'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_nombre', sa.String(length=255), nullable=False),
    sa.Column('actor_rol', sa.String(length=50), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.String(length=36), nullable=False),
    sa.Column('proyecto_id', sa.String(length=36), nullable=True),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('folio', sa.Integer(), nullable=False),
    sa.Column('device_ts', sa.DateTime(), nullable=True),
    sa.Column('synced_offline', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['usuarios.id'], name=op.f('fk_audit_log_actor_id_usuarios')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_audit_log_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log')),
    sa.UniqueConstraint('empresa_id', 'folio', name='uq_audit_log_empresa_folio')
    )
    op.create_table('empresa_usuario',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'coordinador', 'residente', 'trabajador', name='rol', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'inactivo', name='estado', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_empresa_usuario_empresa_id_empresas')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_empresa_usuario_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresa_usuario'))
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('evento', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('email_enviado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_notificaciones_empresa_id_empresas')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_notificaciones_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notificaciones'))
    )
    op.create_table('proyectos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ubicacion_nombre', sa.String(length=500), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('coordinador_principal_id', sa.String(length=36), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'pausado', 'cerrado', name='estado', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin_estimada', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coordinador_principal_id'], ['usuarios.id'], name=op.f('fk_proyectos_coordinador_principal_id_usuarios')),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], name=op.f('fk_proyectos_created_by_usuarios')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_proyectos_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proyectos'))
    )
    op.create_table('items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('proyecto_id', sa.String(length=36), nullable=False),
    sa.Column('parent_item_id', sa.String(length=36), nullable=True),
    sa.Column('nivel_profundidad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('asignado_a', sa.String(length=36), nullable=True),
    sa.Column('estado', sa.Enum('abierto', 'en_progreso', 'pendiente_revision', 'terminado', 'problema', name='estado', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('estado_previo', sa.Enum('abierto', 'en_progreso', 'pendiente_revision', 'terminado', 'problema', name='estado_previo', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('fecha_inicio_estimada', sa.Date(), nullable=True),
    sa.Column('duracion_estimada_horas', sa.Float(), nullable=True),
    sa.Column('fecha_limite', sa.Date(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asignado_a'], ['usuarios.id'], name=op.f('fk_items_asignado_a_usuarios')),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], name=op.f('fk_items_created_by_usuarios')),
    sa.ForeignKeyConstraint(['parent_item_id'], ['items.id'], name=op.f('fk_items_parent_item_id_items')),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], name=op.f('fk_items_proyecto_id_proyectos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items'))
    )
    op.create_table('proyecto_usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('proyecto_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('rol_en_proyecto', sa.Enum('admin', 'coordinador', 'residente', 'trabajador', name='rol_en_proyecto', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], name=op.f('fk_proyecto_usuarios_proyecto_id_proyectos')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_proyecto_usuarios_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proyecto_usuarios'))
    )
    op.create_table('item_comentarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('device_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_comentarios_item_id_items')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_item_comentarios_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_comentarios'))
    )
    op.create_table('item_evidencias',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('s3_url', sa.String(length=1000), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('sync_status', sa.Enum('pendiente', 'subida', 'error', name='sync_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('device_timestamp', sa.DateTime(), nullable=False),
    sa.Column('server_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_evidencias_item_id_items')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_item_evidencias_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_evidencias'))
    )
    op.create_table('item_historial',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('estado_anterior', sa.String(length=50), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=50), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_historial_item_id_items')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_item_historial_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_historial'))
    )
    op.create_table('item_problemas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('reportado_por', sa.String(length=36), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('abierto', 'cerrado', name='estado', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('cerrado_por', sa.String(length=36), nullable=True),
    sa.Column('cerrado_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cerrado_por'], ['usuarios.id'], name=op.f('fk_item_problemas_cerrado_por_usuarios')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_problemas_item_id_items')),
    sa.ForeignKeyConstraint(['reportado_por'], ['usuarios.id'], name=op.f('fk_item_problemas_reportado_por_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_problemas'))
    )
    op.create_table('sync_conflictos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('cambio_local', sa.JSON(), nullable=False),
    sa.Column('cambio_servidor', sa.JSON(), nullable=False),
    sa.Column('dispositivo_id', sa.String(length=255), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'resuelto', name='estado', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('resuelto_por', sa.String(length=36), nullable=True),
    sa.Column('resuelto_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_sync_conflictos_item_id_items')),
    sa.ForeignKeyConstraint(['resuelto_por'], ['usuarios.id'], name=op.f('fk_sync_conflictos_resuelto_por_usuarios')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_sync_conflictos_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_conflictos'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_conflictos')
    op.drop_table('item_problemas')
    op.drop_table('item_historial')
    op.drop_table('item_evidencias')
    op.drop_table('item_comentarios')
    op.drop_table('proyecto_usuarios')
    op.drop_table('items')
    op.drop_table('proyectos')
    op.drop_table('notificaciones')
    op.drop_table('empresa_usuario')
    op.drop_table('audit_log')
    op.drop_table('usuarios')
    op.drop_table('empresas')
    # ### end Alembic commands ###
