"""CTT-117 sync_conflictos add version_ganadora

Revision ID: 9aab29aa04ad
Revises: 239c72c4c89c
Create Date: 2026-09-01 22:05:35.069136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aab29aa04ad'
down_revision: Union[str, Sequence[str], None] = '239c72c4c89c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_conflictos', sa.Column('version_ganadora', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_conflictos', 'version_ganadora')
    # ### end Alembic commands ###
