"""proyecto_usuario: add estado y unique constraint

Revision ID: fd2352cb63a2
Revises: 6aae58b445da
Create Date: 2026-07-19 16:00:13.103021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd2352cb63a2'
down_revision: Union[str, Sequence[str], None] = '6aae58b445da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyecto_usuarios', sa.Column('estado', sa.Enum('activo', 'inactivo', name='proyecto_usuario_estado', native_enum=False, create_constraint=True), nullable=False, server_default='activo'))
    op.create_unique_constraint(op.f('uq_proyecto_usuarios_proyecto_id'), 'proyecto_usuarios', ['proyecto_id', 'usuario_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_proyecto_usuarios_proyecto_id'), 'proyecto_usuarios', type_='unique')
    op.drop_column('proyecto_usuarios', 'estado')
    # ### end Alembic commands ###
