// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema7 extends i0.VersionedSchema {
  Schema7({required super.database}) : super(version: 7);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    syncPendientes,
    itemsCache,
    usuarioActivo,
    syncReconciliacion,
    uxSyncIdempotency,
    ixSyncEnvio,
    ixSyncEntidad,
    ixSyncUsuario,
  ];
  late final Shape0 syncPendientes = Shape0(
      source: i0.VersionedTable(
        entityName: 'sync_pendientes',
        withoutRowId: false,
        isStrict: true,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
          _column_14,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
          _column_22,
          _column_23,
          _column_24,
          _column_25,
          _column_26,
          _column_27,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 itemsCache = Shape1(
      source: i0.VersionedTable(
        entityName: 'items_cache',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_28,
          _column_29,
          _column_30,
          _column_31,
          _column_32,
          _column_33,
          _column_34,
          _column_35,
          _column_36,
          _column_37,
          _column_38,
          _column_39,
          _column_40,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 usuarioActivo = Shape2(
      source: i0.VersionedTable(
        entityName: 'usuario_activo',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_28,
          _column_41,
          _column_42,
          _column_43,
          _column_44,
          _column_3,
          _column_45,
          _column_46,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 syncReconciliacion = Shape3(
      source: i0.VersionedTable(
        entityName: 'sync_reconciliacion',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_28,
          _column_47,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  final i1.Index uxSyncIdempotency = i1.Index('ux_sync_idempotency',
      'CREATE UNIQUE INDEX ux_sync_idempotency ON sync_pendientes (idempotency_key)');
  final i1.Index ixSyncEnvio = i1.Index('ix_sync_envio',
      'CREATE INDEX ix_sync_envio ON sync_pendientes (estado, secuencia)');
  final i1.Index ixSyncEntidad = i1.Index('ix_sync_entidad',
      'CREATE INDEX ix_sync_entidad ON sync_pendientes (tipo_entidad, entidad_id, secuencia)');
  final i1.Index ixSyncUsuario = i1.Index('ix_sync_usuario',
      'CREATE INDEX ix_sync_usuario ON sync_pendientes (usuario_id, estado)');
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get secuencia =>
      columnsByName['secuencia']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get idempotencyKey =>
      columnsByName['idempotency_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get empresaId =>
      columnsByName['empresa_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get usuarioId =>
      columnsByName['usuario_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get instalacionId =>
      columnsByName['instalacion_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tipoEntidad =>
      columnsByName['tipo_entidad']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entidadId =>
      columnsByName['entidad_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get accion =>
      columnsByName['accion']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get payloadVersion =>
      columnsByName['payload_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get versionBase =>
      columnsByName['version_base']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get creadoEnDispositivo =>
      columnsByName['creado_en_dispositivo']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get estado =>
      columnsByName['estado']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get motivo =>
      columnsByName['motivo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get conflictoId =>
      columnsByName['conflicto_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get acknowledged =>
      columnsByName['acknowledged']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<int> get intentosRed =>
      columnsByName['intentos_red']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get intentosServidor =>
      columnsByName['intentos_servidor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get proximoIntentoEn =>
      columnsByName['proximo_intento_en']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get ultimoIntentoEn =>
      columnsByName['ultimo_intento_en']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get ultimoErrorCodigo =>
      columnsByName['ultimo_error_codigo']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get ultimoError =>
      columnsByName['ultimo_error']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tomadoPor =>
      columnsByName['tomado_por']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get tomadoHasta =>
      columnsByName['tomado_hasta']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get sincronizadoEn =>
      columnsByName['sincronizado_en']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get versionResultante =>
      columnsByName['version_resultante']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get rechazoId =>
      columnsByName['rechazo_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>('secuencia', aliasedName, false,
        hasAutoIncrement: true,
        type: i1.DriftSqlType.int,
        defaultConstraints:
            i1.GeneratedColumn.constraintIsAlways('PRIMARY KEY AUTOINCREMENT'));
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>('id', aliasedName, false,
        type: i1.DriftSqlType.string,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways('UNIQUE'));
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>('idempotency_key', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>('empresa_id', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>('usuario_id', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>('instalacion_id', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>('tipo_entidad', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>('entidad_id', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>('accion', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>('payload', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>('payload_version', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>('version_base', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<DateTime> _column_12(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('creado_en_dispositivo', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>('estado', aliasedName, false,
        type: i1.DriftSqlType.string,
        defaultValue: const CustomExpression('\'pendiente\''));
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>('motivo', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>('conflicto_id', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_16(String aliasedName) =>
    i1.GeneratedColumn<bool>('acknowledged', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("acknowledged" IN (0, 1))'),
        defaultValue: const CustomExpression('0'));
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>('intentos_red', aliasedName, false,
        type: i1.DriftSqlType.int, defaultValue: const CustomExpression('0'));
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>('intentos_servidor', aliasedName, false,
        type: i1.DriftSqlType.int, defaultValue: const CustomExpression('0'));
i1.GeneratedColumn<DateTime> _column_19(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('proximo_intento_en', aliasedName, true,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<DateTime> _column_20(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('ultimo_intento_en', aliasedName, true,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>('ultimo_error_codigo', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>('ultimo_error', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>('tomado_por', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<DateTime> _column_24(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('tomado_hasta', aliasedName, true,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<DateTime> _column_25(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('sincronizado_en', aliasedName, true,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>('version_resultante', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>('rechazo_id', aliasedName, true,
        type: i1.DriftSqlType.string);

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get proyectoId =>
      columnsByName['proyecto_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get proyectoNombre =>
      columnsByName['proyecto_nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get parentItemId =>
      columnsByName['parent_item_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get nivelProfundidad =>
      columnsByName['nivel_profundidad']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get descripcion =>
      columnsByName['descripcion']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get asignadoA =>
      columnsByName['asignado_a']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get estado =>
      columnsByName['estado']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get estadoPrevio =>
      columnsByName['estado_previo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get tieneConflicto =>
      columnsByName['tiene_conflicto']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get cachadoEn =>
      columnsByName['cachado_en']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>('id', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>('proyecto_id', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>('proyecto_nombre', aliasedName, false,
        type: i1.DriftSqlType.string,
        defaultValue: const CustomExpression('\'\''));
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>('parent_item_id', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>('nivel_profundidad', aliasedName, false,
        type: i1.DriftSqlType.int, defaultValue: const CustomExpression('0'));
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>('nombre', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>('descripcion', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>('asignado_a', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>('estado', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>('estado_previo', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_38(String aliasedName) =>
    i1.GeneratedColumn<bool>('tiene_conflicto', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("tiene_conflicto" IN (0, 1))'),
        defaultValue: const CustomExpression('0'));
i1.GeneratedColumn<DateTime> _column_39(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('updated_at', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<DateTime> _column_40(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('cachado_en', aliasedName, false,
        type: i1.DriftSqlType.dateTime);

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get firebaseUid =>
      columnsByName['firebase_uid']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nombreCompleto =>
      columnsByName['nombre_completo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get email =>
      columnsByName['email']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rolActual =>
      columnsByName['rol_actual']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get empresaId =>
      columnsByName['empresa_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get empresaNombre =>
      columnsByName['empresa_nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get esSuperAdmin =>
      columnsByName['es_super_admin']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>('firebase_uid', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>('nombre_completo', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>('email', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>('rol_actual', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>('empresa_nombre', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_46(String aliasedName) =>
    i1.GeneratedColumn<bool>('es_super_admin', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("es_super_admin" IN (0, 1))'),
        defaultValue: const CustomExpression('0'));

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get ultimaReconciliacion =>
      columnsByName['ultima_reconciliacion']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<DateTime> _column_47(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('ultima_reconciliacion', aliasedName, true,
        type: i1.DriftSqlType.dateTime);
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 6:
        final schema = Schema7(database: database);
        final migrator = i1.Migrator(database, schema);
        await from6To7(migrator, schema);
        return 7;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
}) =>
    i0.VersionedSchema.stepByStepHelper(
        step: migrationSteps(
      from6To7: from6To7,
    ));
